name: isochron_cli
description: A synthesis-based forced aligner CLI.
version: 0.0.1
# repository: https://github.com/your_username/isochron

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  # Fast Fourier Transform (FFT) implementation
  fftea: ^1.4.0
  unorm_dart: ^0.3.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0