name: isochron_flutter
description: "A synthesis-based forced aligner for desktop"
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.8
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  path: ^1.9.1
  
  # Our Local Engine
  isochron_cli:
    path: ../isochron_cli

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

